vault:
  injector:
    enabled: false
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host vault.lmilius.com
      tls:
        - secretName: vault-tls-certificate
          hosts:
            - *host
